language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
  - npm install -g gulp web-component-tester
  - npm install
  - gulp test
script: xvfb-run wct
deploy:
  provider: firebase
  edge: true
  skip_cleanup: true
  token: "${TOKEN}"
  project: "${PROJECT_ID}"
  on:
    branch: master
