sudo: false
language: node_js
node_js:
  - "6.1"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - node run build
  - node test
deploy:
  provider: firebase
  edge: true
  skip_cleanup: true
  token: "${TOKEN}"
  project: "${PROJECT_ID}"
  on:
    branch: master
